name: hyp3-sdk
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-cov
  - responses
  # For running
  - colorama # [win]
  - python-dateutil
  - requests
  - tqdm
  - urllib3
  - pip:
    # For packaging and testing
    - s3pypi
