name: hyp3-sdk
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-cov
  # For running
  - importlib_metadata
  - requests
  - pip:
    # for packaging and testing
    - s3pypi
    - safety
