name: Distribute to PyPI

on:
  push:
    tags:
      - v*

jobs:
  distribute:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml

      - name: Build distribution
        id: build
        run: |
          python -m build

      - name: upload to PyPI.org
        uses: pypa/gh-action-pypi-publish@v1.14.1
        with:
          user: __token__
          password: ${{ secrets.TOOLS_PYPI_PAK }}
