name: Notify Downstream of New Release

on:
  release:
    types:
      - released

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Bump SDK version in HyP3 docs
        uses: benc-uk/workflow-dispatch@v1.2
        with:
          workflow: update_sdk_version.yml
          token: ${{ secrets.TOOLS_BOT_PAK }}
          repo: ASFHyP3/hyp3-docs
          ref: main
          inputs: '{"sdk_version": "${{ github.event.release.tag_name }}"}'
